### ISSUE TITLE
How do I inject the code?

### ISSUE THREAD

**Issue by etayl221** [SnowLord7/Boxel-Rebound-Cheat#2]
Hi,

I've recently tried to inject the script/code but couldn't work out how to do it.

If someone could explain how that would be great!

Thanks.

**Comment by SnowLord7** [comment]
Already answered [here](https://github.com/SnowLord7/Boxel-Rebound-Cheat/issues/1).

> Open the developer console for the extension and paste the script.
> 
> After injecting the code make sure to open the GUI by pressing the ~ key.

**Comment by etayl221** [comment]
It says undefined
